package:
  name: data-science-utils
  version: 0.0.1
source:
  git_url: git@bitbucket.org:antifragileseeker/data-science-utils.git
  git_rev: 2629b30

requirements:
  build:
    - python
    - setuptools
    - scipy
    - bokeh
    - seaborn
    - pandas
    - scikit-learn
    - numpy
    - jupyter
    - matplotlib
    - sqlalchemy
    - -e git+git@github.com:greytip/statsmodels.git#egg=statsmodels   - psycopg2

about:
  license:  See Licences.TXT
  summary: some wrappers, and library functions used in a data science workflow
